
# Notes on how to authenticate remotely
# taken from here: https://stackoverflow.com/questions/70399016/k3s-kubeconfig-authenticate-with-token-instead-of-client-cert

kubectl create serviceaccount cluster-admin

kubectl create clusterrolebinding cluster-admin-manual --clusterrole=cluster-admin --serviceaccount=default:cluster-admin

kubectl get serviceaccount cluster-admin -o yaml

kubectl create token cluster-admin

user:
puth that into the token
eyJhbGciOiJSUzI1NiIsImtpZCI6InV6LW41em94QmF3UFVvRlJFSWtnRVl2ZndzanBsbFh6cnhwZFF4dnAxQ1kifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxNzQyMzI4NTY0LCJpYXQiOjE3NDIzMjQ5NjQsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiMDUxOTk5ZWQtYWNiZS00ZWY1LWFkYTktMmE1YTMyYzVhNWRkIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImNsdXN0ZXItYWRtaW4iLCJ1aWQiOiJiMzQyOTYwMS1lYTI0LTRhZmMtYWRkMy0yZGM5Y2ZhODIwOWEifX0sIm5iZiI6MTc0MjMyNDk2NCwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6Y2x1c3Rlci1hZG1pbiJ9.ioKSNaW1w5FOsGsGxSwuC4g5YVyQ3cVAQaRsfbGYUjjk27Vpvx8Y3iFo9r64ocACERzmtjLq9ut04eTgxJ8apeGo_Wu2vcnPfMrgpyE2QetDOpAdTKTXY0UjNPcNH33pbsV_ETLbTTs2JvsoZ1srUZLbI3066JekDyJjxzgyCOkUgk65TBJ_KStD4mUos5NSTts4fIghr-jR6Ui-jQ7FPZzhv4dbJ25fALi1arjMlMZ9aZBoa1FqWryZif5Y7A_e_5YWCzvoF2nb2k4ioXagrbamhywBhYJC4dRZIxTpOXEVrJJSRVElytWvOHpfJfXWE784CZwDIFEgky4vO3KdRw


---
apiVersion: v1
clusters:
- cluster:
    server: k8sapi.placeholder
  name: k8s-playground
contexts:
- context:
    cluster: k8s-playground
    user: k8s-playground
  name: k8s-playground
current-context: default
kind: Config
preferences: {}
users:
- name: k8s-playground
  user:
    token: token.placeholder