
# Notes on how to authenticate remotely
# taken from here: https://stackoverflow.com/questions/70399016/k3s-kubeconfig-authenticate-with-token-instead-of-client-cert

#TODO: Create bash, create function and add it to the functions file.
kubectl create serviceaccount cluster-admin

kubectl create clusterrolebinding cluster-admin-manual --clusterrole=cluster-admin --serviceaccount=default:cluster-admin

kubectl get serviceaccount cluster-admin -o yaml

kubectl create token cluster-admin

user:
puth that into the token

---
apiVersion: v1
clusters:
- cluster:
    server: k8sapi.placeholder
  name: k8s-playground
contexts:
- context:
    cluster: k8s-playground
    user: k8s-playground
  name: k8s-playground
current-context: default
kind: Config
preferences: {}
users:
- name: k8s-playground
  user:
    token: token.placeholder