apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin
  name: admin
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30495
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: admin
  sessionAffinity: None
  type: NodePort
