apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31680
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api
  sessionAffinity: None
  type: NodePort