apiVersion: v1
kind: Service
metadata:
  labels:
    app: game
  name: game
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31825
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: game
  sessionAffinity: None
  type: NodePort